### ISSUE TITLE
Can't install rubies

### ISSUE THREAD

**Issue by wkhatch** [remear/jewelrybox#151]
While trying to resolve a readline related issue, I decided to reinstall 1.9.2 head. The app crashed. After starting it again, I clicked Add Ruby, selected 1.9.2 head again, install, and the "Add Ruby" view just goes blank gray after beginning the install. I'm unsure if it's actually doing anything yet, but it seems like it would present status, etc, so I'm assuming the blank gray state is not normal. 

UPDATE: I had to update  rvm, then do the work around with brew for lack of gcc, etc, and now it's fine.

**Comment by remear** [comment]
No, it's not normal. It was introduced back when RVM added more output to advise users they need to do exactly what you did and what's stated in rvm requirements, which is, install gcc preferably via homebrew, etc.

I believe this is fixed in v1.4 but I've yet to have anyone respond back to me confirming such. Feel free to move to the v1.4 beta. I've fixed other issues introduced in newer RVM versions you're likely to encounter. http://dl.dropbox.com/u/5676052/JewelryBox_v1.4.1443.zip

**Comment by 0xbs0d** [comment]
I had the same problem. After installing gcc with brew and updating do 1.4beta it all seems to work just fine.
