### ISSUE TITLE
Crash when managing gemsets

### ISSUE THREAD

**Issue by mfellner** [remear/jewelrybox#152]
I just installed JewelryBox 1.3 (2156) on OS X 10.8.2 and also installed rvm via the GUI (didn't have it installed before).

I added Ruby 1.9.3-p327 and set it as default. When I try to click on the second element `=> (default)` in the listing under _Gemsets_ the application crashes due to the following error:
`Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringFromIndex:]: Range or index out of bounds'`
The other two list elements work fine and I encountered no further issues. I attached the log and a screenshot below.

[Error Log (Dropbox)](https://www.dropbox.com/s/ltyj3vwu87keyfm/error.log)

![Screenshot](http://i.imgur.com/4Gs0d.png)

**Comment by remear** [comment]
Could you try the 1.4 beta. https://dl.dropbox.com/s/c8zu7ua9wa9t07x/JewelryBox_v1.4_1427.zip?dl=1

**Comment by mfellner** [comment]
Unfortunately the issue persists in 1.4. Here is the [log](https://www.dropbox.com/s/hmwsvwvkopaxd94/error2.log).

**Comment by remear** [comment]
It seems, once again, that the behavior of gemset listings was recently changed in RVM. I'll have to rewrite the parser to accomodate the changes. Stay tuned. I might take care of this today.

**Comment by remear** [comment]
Can you try this build. http://dl.dropbox.com/u/5676052/JewelryBox_v1.4.1443.zip

**Comment by mfellner** [comment]
Thanks, build 1443 resolved the issue for me! The listing now contains all the correct gemsets and there is no crash anymore. ![screenshot](http://i.imgur.com/4SpTZ.png)

**Comment by remear** [comment]
Great! Thanks for helping test. I'll probably be releasing v1.4 this week some time so watch for that on http://jewelrybox.unfiniti.com or an announcement via @remear or @unfiniti.

**Comment by dlivesay** [comment]
I'm getting almost that same error in 10.6.8. The only difference is that it says "NSCFString" instead of "NSCFConstantString." The steps to reproduce are the same.
Here's the crash report:

Application Specific Information:
abort() called
objc[68834]: garbage collection is ON
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[NSCFString substringFromIndex:]: Range or index out of bounds'

I have the following rubies installed:

   jruby-1.6.5 [ x86_64 ]
   jruby-1.6.5.1 [ x86_64 ]
   ruby-1.8.7-p371 [ i686 ]
   ruby-1.9.1-p431 [ i386 ]
=\* ruby-1.9.3-p327 [ x86_64 ]
