### ISSUE TITLE
Multi-user Install 

### ISSUE THREAD

**Issue by nskousen** [remear/jewelrybox#166]
FAQ says multi-user install is supported, only installs as single user (self), and does not see or recognize Ruby 1.8.6 (Apple), or Ruby 1.9.3 installed previously as root for Metasploit and other projects.   How do I expand JewelryBox scope to include root / all users ?  -Niel

**Comment by remear** [comment]
Hi Neil,

JewelryBox supports both multi-user and single-user installations. However, if you want JewelryBox to install RVM for you, it will only do a single-user installation. This is because we really haven't found a way with which we are satisfied to initiate the installation as a privileged user.

If you want to use JewelryBox with a multi-user installation of RVM, you'll have to set it up yourself via the command line, add you user to the rvm group, and follow whatever other directions RVM mentions during the installation process. Then you should be able to launch JewelryBox and use it with your multi-user installation. Most JewelryBox users stick to single-user installations so mutli-user support is far less tested. If you encounter any problems, please open issues here.

**Comment by nskousen** [comment]
Hi Ben,  Thanks for the info.   

I presume that having a single user install via JewelryBox complicates life given that the root user and system wide installs are for apple's core 1.8.6 and my cli installed 1.9.3.

Would you recommend that I uninstall the single user RVM from my local user, then go back and to the root user, add RVM and go from there ?

Thanks
Niel

**Comment by remear** [comment]
What exactly is it you're trying to do?

**Comment by nskousen** [comment]
I have Metasploit (ruby 1.9.3) running on the box, and we have some Rails apps and Ruby scripts in my work environment have appear to be more gem set intolerant that some.   prior to setting these up and doing some testing on my box I wanted to be able to use RVM to keep my package sets easier to work with - given that I dont really know what all is coming in pulling these rails app's (git clone) in from the centos box's their running on in dev / test / and production.

Also some thoughts about diving more deeply into ruby myself, hence get a better handle and tool on the overall framework before I totally clutter it all up  8=)

**Comment by nskousen** [comment]
certainly no problem to just stay with cli rvm ....    just starting / playing with the whole rvm mac os x

Niel

**Comment by remear** [comment]
A single-user installation should be fine. None of that sounds like you need a multi-user installation.

Just install RVM, via JewelryBox if you prefer, and follow RVM notes (In JewelryBox open the dashboard and click "Release Notes". You'll probably want to install homebrew as it suggests.

```
brew update
brew tap homebrew/dupes
brew install autoconf automake apple-gcc42
rvm pkg install openssl
```

Then install whatever rubies and patches you want. JewelryBox makes this easier than on the command line.

After that, go to the gemsets area and create gemsets in the proper rubies for everything you want to isolate into it's own "sandbox".

Since JewelryBox offers no package management currently, you'll still have to open your project directory and do `rvm use RUBYNAME@GEMSET` or create a .rvmrc in that folder to do that for you each time you cd to that directory.

Note that installing RVM this way leaves your system installed ruby untouched. You'll still be able to access it via rvm use system.

**Comment by remear** [comment]
@nskousen Were you able to get everything set up?

**Comment by nskousen** [comment]
not yet, back on it this weekend...   been slammed on other work priorities this week

thanks for checking back with me

Niel

**Comment by remear** [comment]
Closing this. If you have other trouble, ping me on twitter.
