### ISSUE TITLE
"The update is improperly signed" error

### ISSUE THREAD

**Issue by EthanMichaels** [remear/jewelrybox#171]
Jewelry Box 1.3

Build 2156

RVM version 1.17.9

When I launch Jewelry Box I get a dialog saying there's a new version...

![jewelry_box_update](https://f.cloud.github.com/assets/1093426/162534/09db1b4e-77bf-11e2-9a81-16b74316cd84.jpg)

When I click "install update" there's indication of downloading, then I get this error dialog...

![jewelry_box_error](https://f.cloud.github.com/assets/1093426/162536/26f4349a-77bf-11e2-92f3-5190c38a167b.jpg)

**Comment by remear** [comment]
Assuming you're using OS X 10.7 or newer...

The updater changed between 1.4 and 1.4.1 since signing updates is a huge pain. The update framework now looks for a developer-signed binary, which should make releasing JewelryBox updates much easier. It's possible that attempting to upgrade from 1.3 to 1.4.1 through the update framework won't work properly, despite the fact that I spent a week testing the upgrade from 1.3 to 1.4 and 1.4 to 1.4.1. The easiest thing would be for you to just download JewelryBox again from the site and drop it in your applications folder.

**Comment by EthanMichaels** [comment]
Thanks for the reply. I'm using Mac OS 10.7.5.

I'd be happy to download Jewelry Box directly from http://jewelrybox.unfiniti.com, but I'm sorry to say there's some text on the web page that's unclear to me:

"Does not work with newer versions of RVM. Use RVM ~1.16.x"

I have RVM 1.17.9 installed. So does that mean I should avoid upgrading Jewelry Box?

What does "~" mean?

What's your advice on the optimal RVM and Jewelry Box versions to install?

**Comment by remear** [comment]
I'm working on clarifying the text so it won't be confusing. It means the following:

OS X 10.6 support has been terminated and the last version of JewelryBox that will run on 10.6 is 1.3. Version 1.3 works best with a maximum RVM version around 1.16.x. If you attempt to use anything newer, results may vary and you'll experience more crashes.

JewelryBox 1.4 and newer supports only OS X 10.7 or newer and supports the latest RVM, apart from issues filed here that we're working on fixing for future updates.

So, for you, I suggest grabbing JewelryBox 1.4.1 from the site and use the latest RVM stable. If you run into any crashes or problems, open issues here with detailed information for reproducing the issue and your system info.

**Comment by EthanMichaels** [comment]
OK, that helps. Thanks for the info.
