### ISSUE TITLE
Can't choose default gemset when setting default ruby

### ISSUE THREAD

**Issue by zanshin** [remear/jewelrybox#75]
Under the Gemsets tab I can see three gemsets for ruby-1.9.2-p180: default, global, and twitter-bootstrap. I want to make ruby-1.9.2-p180 my default ruby using the default gemset. The Manage Rubies tab only allows me to set with global or twitter-bootstrap as the gemset and, what's worse, there is no way to reset the default setting. So now my entire rvm installation is broken.

**Comment by remear** [comment]
Switch your default ruby from the system menu bar. Switching to just the ruby name in the list will make that ruby the default ruby with its default gemset. From the command-line, running `rvm use ruby-1.9.2-p180 --default` would make it use ruby-1.9.2-p180 with its default gemset.

Normally you wouldn't want to use the default gemset because you won't be taking advantage of inheritance in gemsets. All gemsets inherit from the global gemset and not the default gemset. This area is marked for UI redesign, which I'm working on for the next release. If I keep the same functionality in that area, I'll add the default gemset in the drop down menu you see when managing a Ruby.

**Comment by remear** [comment]
Fixed in 1.3
